### ISSUE TITLE
:lady_beetle: Bug: failure to delete alert emails if there are multiples with the same address

### ISSUE THREAD

**Issue by shoriminimoe** [ScaleComputing/HyperCoreAnsibleCollection#264]
## Describe the bug
The collection is unable to delete an alert email if a duplicate is present.

**To Reproduce**
1. Start with a cluster containing multiple duplicate alert email targets
2. Attempt to delete one using the email_alert module
3. Delete fails

## Expected behavior
The collection should be able to delete an alert email when there are duplicates

## Screenshots
Example with duplicate emails
![image](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/assets/16456474/c582e43d-a065-404f-8c2d-5dea0673b589)

Attempting to delete the email address with the following playbook results in a failure
```yaml
---
- name: Delete alert email
  hosts: all
  connection: local
  gather_facts: false
  environment:
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ sc_username }}"
    SC_PASSWORD: "{{ sc_password }}"
​
  tasks:
    - name: Delete alert email
      scale_computing.hypercore.email_alert:
        state: absent
        email: alerts3@scalecomputing.com
```

Failure message:
![image](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/assets/16456474/1929530d-0ef5-418c-9d60-4b9bae2d8fdf)

## System Info (please complete the following information):
 - OS: Pop!_OS 22.04
 - HyperCore Version: 9.2.22+
 - Ansible Version: 2.14.1
 - Collection Version 1.3.0
