### ISSUE TITLE
:lady_beetle: Bug: masked password appears in unrelated output

### ISSUE THREAD

**Issue by shoriminimoe** [ScaleComputing/HyperCoreAnsibleCollection#270]
## Describe the bug
If the password of the user running a playbook appears in an alert email address, VM name, etc. the portion of output that contains the password is masked.

**To Reproduce**
1. Create an alert email or VM whose name contains a user's password
2. Use that user to read the created email/VM using the appropriate ansible module.
3. The user's password will be masked in the output email/VM name

## Expected behavior
The collection should not be masking passwords in unrelated content.

## Screenshots
Here is an example playbook. The screenshot below has example output
```yaml
---
- name: test masked password output
  hosts: all
  connection: local
  gather_facts: false
  environment:
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ sc_username | default('someuser') }}"
    SC_PASSWORD: "{{ sc_password | default('password') }}"

  tasks:
    - name: "create alert email: mypasswordmanager@example.com"
      scale_computing.hypercore.email_alert:
        email: mypasswordmanager@example.com
        state: present
      register: alert_email

    - name: "Inspect email output"
      debug:
        msg: "Reported email address: '{{ alert_email.record.email }}'"

    - name: "create VM: the-password-manager-vm"
      scale_computing.hypercore.vm:
        state: present
        vm_name: the-password-manager-vm
        description: The name of this VM contains the test user's password
        tags:
          - mypasswordmanager
        vcpu: 2
        memory: "{{ '512 MB' | human_to_bytes }}"
        disks:
          - type: virtio_disk
            disk_slot: 0
            size: "{{ '100 GB' | human_to_bytes }}"
          - type: ide_cdrom
            disk_slot: 0
        nics:
          - type: virtio
      register: vm_created

    - name: "Inspect VM output"
      debug:
        msg:
          - "New VM name: {{ vm_created.record[0].vm_name }}"
          - "New VM tags: {{ vm_created.record[0].tags }}"
          - "New VM description: {{ vm_created.record[0].description }}"
```
![image](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/assets/16456474/487d72d8-28da-466f-9497-4ed5c4366d71)

## System Info (please complete the following information):
 - HyperCore Version: 9.2+
 - Ansible Version: 2.14.1
 - Collection Version: 1.4.0-dev (commit 0670cdc)

## Additional context
This is concerning for a few reasons:
- The password is masked in contexts that can be cross-referenced from other sources. This could reveal the user's password.
- An affected user is unable to reference objects by the name reported by the collection because it is masked. Using the example above, attempting to delete the created email address using this task will silently pass because the email address with the masking characters does not exist:
```yaml
    - name: "Delete created email"
      scale_computing.hypercore.email_alert:
        email: "{{ alert_email.record.email }}"
        state: absent
```
