### ISSUE TITLE
vm_disk does not report changed=true when ISO is detached

### ISSUE THREAD

**Issue by justinc1** [ScaleComputing/HyperCoreAnsibleCollection#29]
From `.../ansible_collections/scale_computing/hypercore/tests/integration/targets/vm_disk/tasks/main.yml`:
```
    - name: Detach ISO image from the disk
      scale_computing.hypercore.vm_disk:
        vm_name: vm-integration-test-disks
        items:
          - disk_slot: 0
            type: ide_cdrom
        state: absent
      register: result
    - ansible.builtin.assert:
        that:
          - result is succeeded
          # - result is changed
          - result.record.0.iso_name == ""
```

The result should be changed, but it is not.
